\input texinfo
@setfilename documentation.info
@documentencoding UTF-8

@settitle Smart Calc v2.0

@titlepage
@title Smart Calc v2.0
@subtitle «Good calculator»
@author lavondas

@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@headings off

@contents

@ifnottex
@node Top
@top Smart Calc v2.0
@insertcopying
@end ifnottex

@menu
* Calculator::
* Graph Plot::
* Credit Calculator::
* Deposit Calculator::
@end menu

@node Calculator
@chapter Calculator

@cindex intro
Калькулятор

@itemize @bullet
@item На вход программы могут подаваться как целые числа, так и вещественные числа, записанные и через точку, и в экспоненциальной форме записи. @*
@item Ввод данных производится в помощью клавиатуры и кнопкок в приложении.  @*
@item У пользователя есть возможность ввода до 255 символов. @*
@item Допускается некорректный ввод.
@item При некорректном вводе будет отображена ошибка после нажатия на символ '=' или нажатия клавиши 'enter' . @*
@item Вычисление производится после полного ввода вычисляемого выражения и нажатия на символ '=' или нажатия клавиши 'enter'. @*
@item Поддерижвается вычисление произвольных скобочных арифметических выражений в инфиксной нотации. @*
@item Поддерижвается вычисление произвольных скобочных арифметических выражений в инфиксной нотации с подстановкой значения переменной x в виде числа. @*

@item Скобочные арифметические выражения в инфиксной нотации поддерживают следующие арифметические операции: @*
@end itemize

@itemize @bullet
@item Скобки: (a + b) @*
@item Сложение: a + b @*
@item Вычитание: a - b @*
@item Умножение: a * b @*
@item Деление: a / b  @*
@item Возведение в степень: a ^ b  @*
@item Остаток от деления: a mod b  @*
@item Унарный минус: -a  @*
@end itemize

@itemize @bullet
@item Скобочные арифметические выражения в инфиксной нотации поддерживают следующие математические функции (скобки обязательны): @*
@item Вычисляет косинус: cos(x)  @*
@item Вычисляет синус: sin(x)  @*
@item Вычисляет тангенс: tan(x)  @*
@item Вычисляет арккосинус: acos(x)  @*
@item Вычисляет арксинус: asin(x) @*
@item Вычисляет арктангенс: atan(x) @*
@item Вычисляет квадратный корень: sqrt(x) @*
@item Вычисляет натуральный логарифм: ln(x) @*
@item Вычисляет десятичный логарифм: log(x) @*
@end itemize

@node Graph Plot
@chapter Graph Plot

@cindex intro
Построение графиков
@itemize @bullet
@item Поддерижвается построение графика функции, заданной с помощью выражения в инфиксной нотации с переменной x. @*
@item Для построения графика функции необходимо дополнительно указать отображаемые область определения, область значения и количество точек. @*
@item Для построения графика функции необходимо нажать кнопку Graph. @*
@end itemize

@node Credit Calculator
@chapter Credit Calculator

@cindex intro
Кредитный калькулятор

@itemize @bullet
@item Поддерживаемые типы кредитов: Аннуитетный, Дифференцированный @*
@item Максимальная сумма кредита: 1,000,000,000,000,000.00 @*
@item Минимальная сумма кредита: 0.00 @*
@item Максимальная ставка: 99.99% @*
@item Минимальная ставка: 0.00% @*
@item Минимальный срок кредита: 600 месяцев @*
@item Максимальный срок кредита: 0 месяцев @*
@item Для расчета необходимо нажать кнопку Calculate@*
@item Для очищения основных полей необходимо нажать Clear@*
@end itemize

@node Deposit Calculator
@chapter Deposit Calculator

@cindex intro
Депозитный калькулятор

@itemize @bullet
@item Максимальная сумма вклада: 1,000,000,000.00 @*
@item Минимальная сумма вклада: 0.00 @*
@item Максимальная ставка: 99.99% @*
@item Минимальная ставка: 0.00% @*
@item Максимальный налоговый процент: 99.99% @*
@item Минимальный налоговый процент: 0.00% @*
@item Максимальный срок: 99 лет @*

@item Для того чтобы добавить пополнения и снятий введите каждую новую сумму и дату и нажмите Add  @*
@item Минимальная сумма неснижаемого остатка 0 @*
@item Максимальная сумма неснижаемого остатка 1,000,000,000.00 @*
@item Для расчета необходимо нажать кнопку Calculate@*
@item Для очищения основных полей необходимо нажать Clear@*
@end itemize

@bye